"""create ip permissions table

Revision ID: acd0513c05bb
Revises:
Create Date: 2022-08-07 16:52:54.328063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'acd0513c05bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_permissions_id'), 'ip_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_ip_permissions_ip_address'), 'ip_permissions', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_permissions_ip_address'), table_name='ip_permissions')
    op.drop_index(op.f('ix_ip_permissions_id'), table_name='ip_permissions')
    op.drop_table('ip_permissions')
    # ### end Alembic commands ###
